// --- DATASETS ---

const INITIAL_THEMES = {
  // === STANDAARD MODUS ===
  clash: {
    label: "Clash Royale",
    icon: "⚔️",
    mode: "normal",
    data: [
        // --- Legendarische Kaarten (Legendary) ---
        { name: "Mega Knight", tier: "legendary", icon: "🛡️" },
        { name: "Log", tier: "legendary", icon: "🪵" },
        { name: "Prinses", tier: "legendary", icon: "👸" },
        { name: "Miner", tier: "legendary", icon: "⛏️" },
        { name: "Sparky", tier: "legendary", icon: "⚡" },
        { name: "Magic Archer", tier: "legendary", icon: "🏹" },
        { name: "Electro Wizard", tier: "legendary", icon: "⚡" },
        { name: "Bandit", tier: "legendary", icon: "🥷" },
        { name: "Night Witch", tier: "legendary", icon: "🦇" },
        { name: "Lumberjack", tier: "legendary", icon: "🪓" },
        { name: "Baby Dragon", tier: "legendary", icon: "🐲" },
        { name: "Ice wizard", tier: "legendary", icon: "❄️" },
        { name: "Lavahound", tier: "legendary", icon: "🌋" },
        { name: "Royal Ghost", tier: "legendary", icon: "👻" },
        // --- Nieuwe Legendarische Kaarten ---
        { name: "Graveyard", tier: "legendary", icon: "💀" },
        { name: "Wallbreakers", tier: "legendary", icon: "💣" },
        { name: "Pheonix", tier: "legendary", icon: "🔥" },
        { name: "Little Prince", tier: "legendary", icon: "👑" },
        { name: "Mother Witch", tier: "legendary", icon: "🐷" },
        { name: "Electro Giant", tier: "legendary", icon: "⚡" },
        { name: "Archer Queen", tier: "legendary", icon: "🏹" },
        { name: "Golden Knight", tier: "legendary", icon: "✨" },
        { name: "Mighty Miner", tier: "legendary", icon: "⛏️" },
        { name: "Monk", tier: "legendary", icon: "🧘" },


        // --- Epische Kaarten (Epic) ---
        { name: "P.E.K.K.A", tier: "epic", icon: "🤖" },
        { name: "Koboldton", tier: "epic", icon: "🛢️" },
        { name: "Skelettenleger", tier: "epic", icon: "💀" },
        { name: "Golem", tier: "epic", icon: "🗿" },
        { name: "Balloon", tier: "epic", icon: "🎈" },
        { name: "X-bow", tier: "epic", icon: "🏹" },
        { name: "Prince", tier: "epic", icon: "🏇" },
        { name: "Witch", tier: "epic", icon: "🧙‍♀️" },
        { name: "Barbarian Barrel", tier: "epic", icon: "🛢️" },
        { name: "Bowler", tier: "epic", icon: "🎳" },
        { name: "Cannon Card", tier: "epic", icon: "🛒" },
        { name: "Dark Prince", tier: "epic", icon: "🛡️" },
        { name: "Executioner", tier: "epic", icon: "🪓" },
        { name: "Guards", tier: "epic", icon: "🛡️" },
        { name: "Giant Skeleton", tier: "epic", icon: "💣" },
        { name: "Hunter", tier: "epic", icon: "🤠" },
        { name: "Clone", tier: "epic", icon: "👯" },
        { name: "Freeze", tier: "epic", icon: "🥶" },
        // --- Nieuwe Epische Kaarten ---
        { name: "Goblin Drill", tier: "epic", icon: "🔨" },
        { name: "Rage", tier: "epic", icon: "😡" },
        { name: "Tornado", tier: "epic", icon: "🌀" },
        { name: "Mirror", tier: "epic", icon: "🪞" },
        { name: "Lightning", tier: "epic", icon: "⚡" },
        { name: "Electro Dragon", tier: "epic", icon: "⚡" },
        { name: "Royal Delivery", tier: "epic", icon: "📦" },
        { name: "Heal Spirit", tier: "epic", icon: "💖" },
        { name: "Battle Healer", tier: "epic", icon: "😇" },
        { name: "Goblin Cage", tier: "epic", icon: "⛓️" },
        { name: "Earthquake", tier: "epic", icon: "🌍" },
        { name: "Fisherman", tier: "epic", icon: "🎣" },
        { name: "Ram Rider", tier: "epic", icon: "🐏" },
        { name: "Royal Hogs", tier: "epic", icon: "🐗" },


        // --- Zeldzame Kaarten (Rare) ---
        { name: "Hog Rider", tier: "rare", icon: "🐖" },
        { name: "Fireball", tier: "rare", icon: "🔥" },
        { name: "Musketier", tier: "rare", icon: "🔫" },
        { name: "Inferno Tower", tier: "rare", icon: "🔥" },
        { name: "Valkyrie", tier: "rare", icon: "🪓" },
        { name: "Rocket", tier: "rare", icon: "🚀" },
        { name: "Wizard", tier: "rare", icon: "🔥" },
        { name: "Battle Ram", tier: "rare", icon: "🐏" },
        { name: "Dart Goblin", tier: "rare", icon: "👺" },
        { name: "Flying Machine", tier: "rare", icon: "🚁" },
        { name: "Giant", tier: "rare", icon: "🥊" },
        { name: "Icegolem", tier: "rare", icon: "⛄" },
        { name: "MEGA Minion", tier: "rare", icon: "⛄" },
        { name: "Mini P.E.K.K.A", tier: "rare", icon: "🥞" },
        { name: "Three Musketiers", tier: "rare", icon: "🔫" },
        { name: "Zappies", tier: "rare", icon: "⚡" },
        // --- Nieuwe Zeldzame Kaarten ---
        { name: "Goblin Hut", tier: "rare", icon: "🛖" },
        { name: "Barbarian Hut", tier: "rare", icon: "🏠" },
        { name: "Tombstone", tier: "rare", icon: "🪦" },
        { name: "Furnace", tier: "rare", icon: "♨️" },
        { name: "Elixir Collector", tier: "rare", icon: "🧪" },
        { name: "Heal", tier: "rare", icon: "❤️" },
        { name: "Poison", tier: "rare", icon: "☣️" },
        { name: "Rascals", tier: "rare", icon: "👧" },
        { name: "Royal Recruits", tier: "rare", icon: "🛡️" },
        { name: "Bomb Tower", tier: "rare", icon: "💣" },
        { name: "Elixir Golem", tier: "rare", icon: "🧪" },
        { name: "Ice Spirit", tier: "rare", icon: "🧊" },


        // --- Algemene Kaarten (Common) ---
        { name: "Elite Barbaren", tier: "common", icon: "⚔️" },
        { name: "Koninklijke Reus", tier: "common", icon: "💂" },
        { name: "Bliksem", tier: "common", icon: "⚡" },
        { name: "Vleermuizen", tier: "common", icon: "🦇" },
        { name: "Pijlen", tier: "common", icon: "🏹" },
        { name: "Mortier", tier: "common", icon: "💣" },
        { name: "Tesla", tier: "common", icon: "⚡" },
        { name: "Boogschutters", tier: "common", icon: "🏹" },
        { name: "Barbaren", tier: "common", icon: "⚔️" },
        { name: "Bommenwerper", tier: "common", icon: "💣" },
        { name: "Vuurgeesten", tier: "common", icon: "🔥" },
        { name: "Koboldbende", tier: "common", icon: "🔪" },
        { name: "Kobolden", tier: "common", icon: "👺" },
        { name: "IJskobold", tier: "common", icon: "❄️" },
        { name: "Ridder", tier: "common", icon: "⚔️" },
        { name: "Dienaren", tier: "common", icon: "🦟" },
        { name: "Diender-hoop", tier: "common", icon: "🦟" },
        { name: "Skeletten", tier: "common", icon: "💀" },
        { name: "Skeletton", tier: "common", icon: "🎈" },
        { name: "Speerkobolden", tier: "common", icon: "🎋" },
        // --- Nieuwe Algemene Kaarten ---
        { name: "Kanon", tier: "common", icon: "💣" },
        { name: "Reus", tier: "common", icon: "💪" },
        { name: "Koningin", tier: "common", icon: "👑" },
        { name: "Goblins", tier: "common", icon: "🗡️" },
        { name: "Spear Goblins", tier: "common", icon: "🎋" },
        { name: "Gaint", tier: "common", icon: "👊" },
        { name: "Royal Guard", tier: "common", icon: "🛡️" },
        { name: "Royal Guard Tower", tier: "common", icon: "🏰" },
        { name: "Cannon", tier: "common", icon: "砲" }
    ]
},
  minecraft: {
    label: "Minecraft",
    icon: "⛏️",
    mode: "normal",
    data: [
      { name: "Diamond Block", tier: "legendary", icon: "💎" },
      { name: "Netherite Sword", tier: "legendary", icon: "🗡️" },
      { name: "Golden Apple", tier: "legendary", icon: "🍎" },
      { name: "Bedrock", tier: "legendary", icon: "🪨" },
      { name: "Beacon", tier: "legendary", icon: "🚨" },
      { name: "Elytra", tier: "legendary", icon: "🕊️" },
      { name: "Trident", tier: "legendary", icon: "🔱" },
      { name: "Totem of Undying", tier: "legendary", icon: "🗿" },
      { name: "Ender Dragon Egg", tier: "legendary", icon: "🥚" },
      { name: "Enchanted Book", tier: "legendary", icon: "📘" },
      { name: "TNT", tier: "epic", icon: "🧨" },
      { name: "Creeper Head", tier: "epic", icon: "🟩" },
      { name: "Ender Pearl", tier: "epic", icon: "🔮" },
      { name: "Slime Block", tier: "epic", icon: "🟢" },
      { name: "Diamond Pickaxe", tier: "epic", icon: "⛏️" },
      { name: "Enchanting Table", tier: "epic", icon: "📖" },
      { name: "Shulker Box", tier: "epic", icon: "📦" },
      { name: "Iron Golem", tier: "epic", icon: "🤖" },
      { name: "Obsidian", tier: "rare", icon: "⬛" },
      { name: "Lava Bucket", tier: "rare", icon: "🌋" },
      { name: "Anvil", tier: "rare", icon: "🔨" },
      { name: "Shield", tier: "rare", icon: "🛡️" },
      { name: "Water Bucket", tier: "rare", icon: "💧" },
      { name: "Dirt Block", tier: "common", icon: "💩" },
      { name: "Wooden Plank", tier: "common", icon: "🪵" },
      { name: "Crafting Table", tier: "common", icon: "🛠️" },
      { name: "Torch", tier: "common", icon: "🕯️" },
      { name: "Chest", tier: "common", icon: "📦" },
      { name: "Furnace", tier: "common", icon: "🔥" },
      { name: "Cobblestone", tier: "common", icon: "🪨" },
      { name: "Bread", tier: "common", icon: "🥖" }
    ]
  },
  kitchen: {
    label: "Keuken",
    icon: "🍳",
    mode: "normal",
    data: [
      { name: "Espressomachine", tier: "legendary", icon: "☕" },
      { name: "Thermomix", tier: "legendary", icon: "🤖" },
      { name: "Airfryer", tier: "epic", icon: "🍟" },
      { name: "KitchenAid Mixer", tier: "legendary", icon: "🥣" },
      { name: "Koelkast", tier: "common", icon: "❄️" },
      { name: "Vaatwasser", tier: "common", icon: "🍽️" },
      { name: "Broodrooster", tier: "common", icon: "🍞" },
      { name: "Magnetron", tier: "common", icon: "☢️" },
      { name: "Oven", tier: "rare", icon: "🥧" },
      { name: "Blender", tier: "rare", icon: "🥤" },
      { name: "Waterkoker", tier: "common", icon: "🫖" },
      { name: "Frituurpan", tier: "rare", icon: "🍤" },
      { name: "Wafelijzer", tier: "rare", icon: "🧇" },
      { name: "Rijstkoker", tier: "rare", icon: "🍚" },
      { name: "Snijplank", tier: "common", icon: "🪵" },
      { name: "Kaasschaaf", tier: "common", icon: "🧀" },
      { name: "Pizzasnijder", tier: "common", icon: "🍕" },
      { name: "Slowcooker", tier: "epic", icon: "🍲" },
      { name: "Pastamachine", tier: "epic", icon: "🍝" },
      { name: "Staafmixer", tier: "common", icon: "🥢" },
      { name: "Rasp", tier: "common", icon: "🥕" }
    ]
  },
  fruit: {
    label: "Fruit",
    icon: "🍎",
    mode: "normal",
    data: [
      { name: "Banaan", tier: "common", icon: "🍌" },
      { name: "Appel", tier: "common", icon: "🍎" },
      { name: "Drakenfruit", tier: "legendary", icon: "🐲" },
      { name: "Kers", tier: "rare", icon: "🍒" },
      { name: "Ananas", tier: "epic", icon: "🍍" },
      { name: "Watermeloen", tier: "rare", icon: "🍉" },
      { name: "Aardbei", tier: "common", icon: "🍓" },
      { name: "Druif", tier: "epic", icon: "🍇" },
      { name: "Citroen", tier: "common", icon: "🍋" },
      { name: "Perzik", tier: "rare", icon: "🍑" },
      { name: "Kiwi", tier: "rare", icon: "🥝" },
      { name: "Kokosnoot", tier: "epic", icon: "🥥" },
      { name: "Avocado", tier: "epic", icon: "🥑" },
      { name: "Mango", tier: "rare", icon: "🥭" },
      { name: "Peer", tier: "common", icon: "🍐" },
      { name: "Sinaasappel", tier: "common", icon: "🍊" },
      { name: "Blauwe Bes", tier: "common", icon: "🫐" },
      { name: "Limoen", tier: "common", icon: "🍈" },
      { name: "Granaatappel", tier: "epic", icon: "☄️" },
      { name: "Papaya", tier: "rare", icon: "🥔" }
    ]
  },
  animals: {
    label: "Dieren",
    icon: "🦁",
    mode: "normal",
    data: [
      { name: "Leeuw", tier: "legendary", icon: "🦁" },
      { name: "Olifant", tier: "epic", icon: "🐘" },
      { name: "Hond", tier: "common", icon: "🐕" },
      { name: "Kat", tier: "common", icon: "🐈" },
      { name: "Haai", tier: "epic", icon: "🦈" },
      { name: "Eenhoorn", tier: "legendary", icon: "🦄" },
      { name: "Varken", tier: "common", icon: "🐖" },
      { name: "Aap", tier: "rare", icon: "🐒" },
      { name: "Pinguïn", tier: "rare", icon: "🐧" },
      { name: "Slang", tier: "rare", icon: "🐍" },
      { name: "T-Rex", tier: "legendary", icon: "🦖" },
      { name: "Kip", tier: "common", icon: "🐔" },
      { name: "Walvis", tier: "epic", icon: "🐋" },
      { name: "Kikker", tier: "common", icon: "🐸" },
      { name: "Uil", tier: "rare", icon: "🦉" },
      { name: "Tijger", tier: "legendary", icon: "🐅" },
      { name: "Giraffe", tier: "epic", icon: "🦒" },
      { name: "Konijn", tier: "common", icon: "🐇" },
      { name: "Beer", tier: "epic", icon: "🐻" },
      { name: "Muis", tier: "common", icon: "🐁" }
    ]
  },
  
  // === HARDMODE THEMA'S ===
  numbers: {
    label: "Getallen",
    icon: "🔢",
    mode: "hard",
    data: [
      { name: "1", tier: "common", icon: "1️⃣" },
      { name: "2", tier: "common", icon: "2️⃣" },
      { name: "3", tier: "common", icon: "3️⃣" },
      { name: "4", tier: "common", icon: "4️⃣" },
      { name: "5", tier: "common", icon: "5️⃣" },
      { name: "6", tier: "common", icon: "6️⃣" },
      { name: "7", tier: "common", icon: "7️⃣" },
      { name: "8", tier: "common", icon: "8️⃣" },
      { name: "9", tier: "common", icon: "9️⃣" },
      { name: "10", tier: "rare", icon: "🔟" },
      { name: "20", tier: "rare", icon: "2️⃣0️⃣" },
      { name: "30", tier: "rare", icon: "3️⃣0️⃣" },
      { name: "40", tier: "rare", icon: "4️⃣0️⃣" },
      { name: "50", tier: "rare", icon: "5️⃣0️⃣" },
      { name: "69", tier: "legendary", icon: "♋" },
      { name: "420", tier: "legendary", icon: "🌿" },
      { name: "360", tier: "epic", icon: "🔄" },
      { name: "365", tier: "common", icon: "📅" },
      { name: "Pi (π)", tier: "legendary", icon: "🥧" },
      { name: "e (2.718)", tier: "epic", icon: "ℯ" },
      { name: "Wortel 2 (√2)", tier: "rare", icon: "📐" },
      { name: "Oneindig (∞)", tier: "legendary", icon: "♾️" },
      { name: "666", tier: "epic", icon: "😈" },
      { name: "0", tier: "common", icon: "0️⃣" },
      { name: "-1", tier: "rare", icon: "➖" },
      { name: "100", tier: "common", icon: "💯" }
    ]
  },
  colors: {
    label: "Kleuren",
    icon: "🎨",
    mode: "hard",
    data: [
      { name: "Rood", tier: "common", icon: "🔴" },
      { name: "Blauw", tier: "common", icon: "🔵" },
      { name: "Geel", tier: "common", icon: "🟡" },
      { name: "Groen", tier: "common", icon: "🟢" },
      { name: "Paars", tier: "rare", icon: "🟣" },
      { name: "Oranje", tier: "common", icon: "🟠" },
      { name: "Zwart", tier: "common", icon: "⚫" },
      { name: "Wit", tier: "common", icon: "⚪" },
      { name: "Grijs", tier: "common", icon: "🐭" },
      { name: "Bruin", tier: "common", icon: "🟤" },
      { name: "Roze", tier: "rare", icon: "🌸" },
      { name: "Turkoois", tier: "epic", icon: "💎" },
      { name: "Goud", tier: "legendary", icon: "🏆" },
      { name: "Zilver", tier: "epic", icon: "🥈" },
      { name: "Brons", tier: "rare", icon: "🥉" },
      { name: "Magenta", tier: "epic", icon: "🔮" },
      { name: "Beige", tier: "rare", icon: "🧥" },
      { name: "Indigo", tier: "legendary", icon: "🌌" },
      { name: "Olijfgroen", tier: "rare", icon: "🫒" },
      { name: "Vantablack", tier: "legendary", icon: "🕳️" }
    ]
  },
  feelings: {
    label: "Gevoelens",
    icon: "🎭",
    mode: "hard",
    data: [
      { name: "Blij", tier: "common", icon: "😄" },
      { name: "Verdrietig", tier: "common", icon: "😢" },
      { name: "Boos", tier: "common", icon: "😡" },
      { name: "Angstig", tier: "common", icon: "😨" },
      { name: "Verrast", tier: "common", icon: "😲" },
      { name: "Walging", tier: "rare", icon: "🤢" },
      { name: "Verliefd", tier: "rare", icon: "😍" },
      { name: "Jaloers", tier: "epic", icon: "😒" },
      { name: "Trots", tier: "rare", icon: "😎" },
      { name: "Eenzaam", tier: "epic", icon: "🥀" },
      { name: "Schuldig", tier: "epic", icon: "😓" },
      { name: "Opgelucht", tier: "rare", icon: "😌" },
      { name: "Nerveus", tier: "rare", icon: "😬" },
      { name: "Euforisch", tier: "legendary", icon: "🤩" },
      { name: "Melancholisch", tier: "legendary", icon: "🌧️" },
      { name: "Dankbaar", tier: "epic", icon: "🙏" },
      { name: "Verveeld", tier: "common", icon: "😑" },
      { name: "Verward", tier: "common", icon: "😕" },
      { name: "Hoopvol", tier: "epic", icon: "🤞" },
      { name: "Nostalgisch", tier: "legendary", icon: "🕰️" }
    ]
  },
  countries: {
    label: "Landen",
    icon: "🌍",
    mode: "hard",
    data: [
      { name: "Nederland", tier: "common", icon: "🇳🇱" },
      { name: "België", tier: "common", icon: "🇧🇪" },
      { name: "Duitsland", tier: "common", icon: "🇩🇪" },
      { name: "Frankrijk", tier: "common", icon: "🇫🇷" },
      { name: "Spanje", tier: "common", icon: "🇪🇸" },
      { name: "Italië", tier: "common", icon: "🇮🇹" },
      { name: "Verenigde Staten", tier: "common", icon: "🇺🇸" },
      { name: "Verenigd Koninkrijk", tier: "common", icon: "🇬🇧" },
      { name: "China", tier: "epic", icon: "🇨🇳" },
      { name: "Japan", tier: "epic", icon: "🇯🇵" },
      { name: "Rusland", tier: "epic", icon: "🇷🇺" },
      { name: "Brazilië", tier: "epic", icon: "🇧🇷" },
      { name: "Australië", tier: "epic", icon: "🇦🇺" },
      { name: "Canada", tier: "rare", icon: "🇨🇦" },
      { name: "Marokko", tier: "rare", icon: "🇲🇦" },
      { name: "Turkije", tier: "rare", icon: "🇹🇷" },
      { name: "Noord-Korea", tier: "legendary", icon: "🇰🇵" },
      { name: "Vaticaanstad", tier: "legendary", icon: "🇻🇦" },
      { name: "Egypte", tier: "rare", icon: "🇪🇬" },
      { name: "Zuid-Afrika", tier: "rare", icon: "🇿🇦" },
      { name: "Zwitserland", tier: "rare", icon: "🇨🇭" }
    ]
  },
  rappers: {
    label: "Rappers",
    icon: "🎤",
    mode: "hard",
    data: [
      { name: "Eminem", tier: "legendary", icon: "👱" },
      { name: "Drake", tier: "epic", icon: "🦉" },
      { name: "Kanye West", tier: "legendary", icon: "🐻" },
      { name: "Jay-Z", tier: "legendary", icon: "👑" },
      { name: "Kendrick Lamar", tier: "epic", icon: "🧬" },
      { name: "Travis Scott", tier: "epic", icon: "🌵" },
      { name: "50 Cent", tier: "rare", icon: "💰" },
      { name: "Snoop Dogg", tier: "legendary", icon: "🌿" },
      { name: "Tupac (2Pac)", tier: "legendary", icon: "🕊️" },
      { name: "The Notorious B.I.G.", tier: "legendary", icon: "👑" },
      { name: "Post Malone", tier: "rare", icon: "🚬" },
      { name: "The Weeknd", tier: "epic", icon: "⭐️" },
      { name: "Dr. Dre", tier: "epic", icon: "🎧" },
      { name: "Cardi B", tier: "common", icon: "👠" },
      { name: "Nicki Minaj", tier: "common", icon: "🦄" },
      { name: "XXXTentacion", tier: "rare", icon: "❌" },
      { name: "Juice WRLD", tier: "rare", icon: "🧃" },
      { name: "Lil Wayne", tier: "epic", icon: "👽" },
      { name: "J. Cole", tier: "epic", icon: "📝" },
      { name: "Future", tier: "rare", icon: "🦅" }
    ]
  },
  math: {
    label: "Wiskunde",
    icon: "📐",
    mode: "hard",
    data: [
      { name: "Stelling van Pythagoras", tier: "common", icon: "📐" },
      { name: "ABC-formule", tier: "common", icon: "🔤" },
      { name: "Laatste stelling van Fermat", tier: "epic", icon: "📚" },
      { name: "Gulden Snede", tier: "epic", icon: "🌀" },
      { name: "Rij van Fibonacci", tier: "rare", icon: "🐚" },
      { name: "Pi (π)", tier: "common", icon: "🥧" },
      { name: "Priemgetallen", tier: "rare", icon: "1️⃣" },
      { name: "Stelling van Thales", tier: "rare", icon: "⭕" },
      { name: "Binomium van Newton", tier: "epic", icon: "🍎" },
      { name: "Eulers Identiteit", tier: "legendary", icon: "🆔" },
      { name: "Vierkleurenstelling", tier: "rare", icon: "🎨" },
      { name: "Riemann-hypothese", tier: "legendary", icon: "❓" },
      { name: "Stelling van Euclides", tier: "epic", icon: "📜" },
      { name: "Integraal", tier: "rare", icon: "∫" },
      { name: "Afgeleide", tier: "rare", icon: "📉" },
      { name: "Kansrekening", tier: "common", icon: "🎲" },
      { name: "Statistiek", tier: "common", icon: "📊" },
      { name: "Sinus & Cosinus", tier: "common", icon: "〰️" },
      { name: "Relativiteitstheorie", tier: "legendary", icon: "🚀" },
      { name: "Schrödingers Kat", tier: "legendary", icon: "🐱" }
    ]
  },
  elements: {
    label: "Elementen",
    icon: "🧪",
    mode: "hard", 
    data: [
      { name: "Goud", tier: "legendary", icon: "🥇" },
      { name: "Uranium", tier: "legendary", icon: "☢️" },
      { name: "Platina", tier: "legendary", icon: "💍" },
      { name: "Plutonium", tier: "legendary", icon: "💣" },
      { name: "Zuurstof", tier: "common", icon: "💨" },
      { name: "Waterstof", tier: "common", icon: "💧" },
      { name: "Helium", tier: "rare", icon: "🎈" },
      { name: "IJzer", tier: "common", icon: "⛓️" },
      { name: "Koolstof", tier: "common", icon: "⚫" },
      { name: "Zilver", tier: "epic", icon: "🥈" },
      { name: "Koper", tier: "rare", icon: "🥉" },
      { name: "Neon", tier: "rare", icon: "🟣" },
      { name: "Kwik", tier: "epic", icon: "🌡️" },
      { name: "Titanium", tier: "epic", icon: "🦾" },
      { name: "Stikstof", tier: "common", icon: "❄️" },
      { name: "Aluminium", tier: "common", icon: "🥫" },
      { name: "Lood", tier: "common", icon: "⚓" },
      { name: "Zwavel", tier: "rare", icon: "🔥" },
      { name: "Chloor", tier: "rare", icon: "🏊" },
      { name: "Calcium", tier: "common", icon: "🥛" },
      { name: "Diamant (Koolstof)", tier: "legendary", icon: "💎" }
    ]
  }
};